main_ingredient_dict = {
    "각종 야채": "all_veggies",
    "아보카도": "avocado",
    "베이컨": "bacon",
    "치즈": "cheese",
    "치킨 브레스트": "chicken_breast",
    "치킨 스트립": "chicken_strip",
    "치킨 데리야끼": "chicken_teriyaki",
    "에그마요": "egg_mayo",
    "햄": "ham",
    "미트볼": "meatball",
    "오믈렛": "omelet",
    "페퍼로니": "pepperoni",
    "풀드포크": "pulled_pork",
    "로스트 비프": "roasted_beef",
    "로티세리 치킨": "rotisserie_chicken",
    "살라미": "salami",
    "스테이크": "steak",
    "참치": "tuna",
    "터키": "turkey",
}
