sandwich_dict = {
    "스파이시 이탈리안 아보카도": "spicy_italian_avocado",
    "터키 베이컨 아보카도": "turkey_bacon_avocado",
    "베지 아보카도": "veggie_avocado",
    "풀드포크": "pulled_pork",
    "에그마요": "egg_mayo",
    "이탈리안 비엠티": "italian_b_m_t",
    "비엘티": "b_l_t",
    "미트볼": "meatball",
    "햄": "ham",
    "참치": "tuna",
    "로티세리 치킨": "rotisserie_chicken",
    "로스트 치킨": "roasted_chicken",
    "로스트 비프": "roasted_beef",
    "써브웨이 클럽": "subway_club",
    "터키": "turkey",
    "베지": "veggie_delite",
    "스테이크 앤 치즈": "steak_and_cheese",
    # "터키 베이컨 아보카도": "turkey_bacon_avocado",
    "치킨 베이컨 랜치": "chicken_bacon_ranch",
    "써브웨이 멜트": "subway_melt",
    "터키 베이컨": "turkey_bacon",
    "스파이시 이탈리안": "spicy_italian",
    "치킨 데리야끼": "chicken_teriyaki",
    "블랙 포레스트햄 앤 에그 치즈": "black_forest_ham_and_egg_cheese",
    "웨스턴 에그 앤 치즈": "western_egg_and_cheese",
    "베이컨 에그 앤 치즈": "bacon_egg_and_cheese",
    "스테이크 에그 앤 치즈": "steak_egg_and_cheese",
}
