sandwich_dict = {
    "스파이시_이탈리안_아보카도": "spicy_italian_avocado",
    "터키_베이컨_아보카도": "turkey_bacon_avocado",
    "베지_아보카도": "veggie_avocado",
    "풀드포크": "pulled_pork",
    "에그마요": "egg_mayo",
    "이탈리안_비엠티": "italian_b_m_t",
    "비엘티": "b_l_t",
    "미트볼": "meatball",
    "햄": "ham",
    "참치": "tuna",
    "로티세리_치킨": "rotisserie_chicken",
    "로스트_치킨": "roasted_chicken",
    "로스트_비프": "roasted_beef",
    "써브웨이_클럽": "subway_club",
    "터키": "turkey",
    "베지": "veggie_delite",
    "스테이크_앤_치즈": "steak_and_cheese",
    # "터키_베이컨_아보카도": "turkey_bacon_avocado",
    "치킨_베이컨_랜치": "chicken_bacon_ranch",
    "써브웨이_멜트": "subway_melt",
    "터키_베이컨": "turkey_bacon",
    "스파이시_이탈리안": "spicy_italian",
    "치킨_데리야끼": "chicken_teriyaki",
    "블랙_포레스트햄_앤_에그_치즈": "black_forest_ham_and_egg_cheese",
    "웨스턴_에그_앤_치즈": "western_egg_and_cheese",
    "베이컨_에그_앤_치즈": "bacon_egg_and_cheese",
    "스테이크_에그_앤_치즈": "steak_egg_and_cheese",
}
