sandwich_dict = {
    "로티세리 치킨": "rotisserie_chicken",
    "풀드포크": "pulled_pork",
    "에그마요": "egg_mayo",
    "이탈리안 비엠티": "italian_b.m.t",
    "비엘티": "b.l.t",
    "미트볼": "meatball",
    "햄": "ham",
    "참치": "tuna",
    # "로티세리 치킨": "rotisserie_chicken",
    "로스트 치킨": "roasted_chicken",
    "로스트 비프": "roasted_beef",
    "써브웨이 클럽": "subway_club",
    "터키": "turkey",
    "베지": "veggie_delite",
    "스테이크 & 치즈": "steak_&_cheese",
    "터키 베이컨 아보카도": "turkey_bacon_avocado",
    "치킨 베이컨 랜치": "chicken_bacon_ranch",
    "써브웨이 멜트": "subway_melt",
    "터키 베이컨": "turkey_bacon",
    "스파이시 이탈리안": "spicy_italian",
    "치킨 데리야끼": "chicken_teriyaki",
    "블랙 포레스트햄 & 에그, 치즈": "black_forest_ham_&_egg,_cheese",
    "웨스턴, 에그 & 치즈": "western,_egg_&_cheese",
    "베이컨, 에그 & 치즈": "bacon,_egg_&_cheese",
    "스테이크, 에그 & 치즈": "steak,_egg_&_cheese",
}
