# Generated by Django 2.0.5 on 2018-08-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookmarkcollection', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarkcollection',
            name='bookmarked_recipe',
            field=models.ManyToManyField(to='recipes.BookmarkedRecipe', verbose_name='북마크 콜렉션'),
        ),
    ]
