# Generated by Django 2.0.5 on 2018-08-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarkcollection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarkcollection',
            name='bookmarked_recipe',
            field=models.ManyToManyField(blank=True, to='recipes.BookmarkedRecipe', verbose_name='북마크 콜렉션'),
        ),
    ]
