# Generated by Django 2.0.5 on 2018-08-12 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmarkcollection', '0002_bookmarkcollection_bookmarked_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarkcollection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
