# Generated by Django 2.1.2 on 2018-11-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarkcollection', '0002_bookmarkcollection_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarkcollection',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
