# Generated by Django 2.1.2 on 2018-11-15 08:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
        ('bookmarkcollection', '0003_auto_20181111_0439'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookmarkCollection',
            new_name='Collection',
        ),
    ]
