# Generated by Django 2.1.2 on 2018-10-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarkcollection', '0003_remove_bookmarkcollection_bookmarked_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarkcollection',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
