# Generated by Django 2.0.5 on 2018-06-25 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='100자까지 Bread 이름을 저장합니다.', max_length=100)),
                ('image', models.ImageField(blank=True, default='', upload_to='')),
            ],
            options={
                'verbose_name_plural': 'bread',
            },
        ),
        migrations.CreateModel(
            name='Cheese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='100자까지 Cheese 이름을 저장합니다.', max_length=100)),
                ('image', models.ImageField(blank=True, default='', upload_to='')),
            ],
            options={
                'verbose_name_plural': 'bread',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toasting', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeBookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('bookmarker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='255자까지 Recipe의 이름을 저장합니다.', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sandwich',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='100자까지 Sandwich의 이름을 저장합니다.', max_length=100, unique=True)),
                ('image', models.FilePathField(blank=True, max_length=1000, path='sandwich')),
            ],
        ),
        migrations.CreateModel(
            name='Sauces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='100자까지 Sauce의 이름을 저장합니다.', max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='100자까지 Topping의 이름을 저장합니다.', max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Vegetables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='100자까지 Vegetable의 이름을 저장합니다.', max_length=100, unique=True)),
                ('quantity', models.CharField(choices=[('LE', 'LESS'), ('NO', 'NORMAL'), ('MO', 'MORE')], default='NO', max_length=2)),
                ('image', models.ImageField(blank=True, default='', upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='bookmarker',
            field=models.ManyToManyField(related_name='bookmarked_recipe', through='recipes.RecipeBookmark', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='bread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.Bread', verbose_name='빵'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cheese',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.Cheese', verbose_name='치즈'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='inventor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_recipe', to=settings.AUTH_USER_MODEL, verbose_name='레시피 제작자'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='liker',
            field=models.ManyToManyField(related_name='liked_recipe', through='recipes.RecipeLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.RecipeName', verbose_name='이름'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='sandwich',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.Sandwich', verbose_name='기본 샌드위치'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='sauces',
            field=models.ManyToManyField(blank=True, to='recipes.Sauces', verbose_name='소스'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='recipes.Toppings', verbose_name='토핑'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='vegetables',
            field=models.ManyToManyField(blank=True, to='recipes.Vegetables', verbose_name='야채'),
        ),
    ]
