# Generated by Django 2.0.5 on 2018-06-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='100자까지 bread의 이름을 저장합니다.', max_length=100)),
            ],
            options={
                'verbose_name_plural': '선택한 bread',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_profile', models.ImageField(blank=True, upload_to='user')),
                ('img_profile_thumbnail', models.ImageField(blank=True, upload_to='user')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeBookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='255자까지 Recipe의 이름을 저장합니다.', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sandwich',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='100자까지 Sandwich의 이름을 저장합니다.', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vegetables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='100자까지 vegetable의 이름을 저장합니다.', max_length=100, unique=True)),
                ('quantity', models.CharField(choices=[('LE', 'LESS'), ('NO', 'NORMAL'), ('MO', 'MORE')], default='NO', max_length=2)),
            ],
            options={
                'verbose_name_plural': '선택한 vegetables',
            },
        ),
    ]
