# Generated by Django 2.1.2 on 2018-10-31 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0001_initial'),
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmarkcollection', '0002_bookmarkcollection_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='bookmarker',
            field=models.ManyToManyField(related_name='bookmarked_recipe', through='recipes.Bookmark', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='bread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingredients.Bread', verbose_name='빵'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cheese',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingredients.Cheese', verbose_name='치즈'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='inventor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_recipe', to=settings.AUTH_USER_MODEL, verbose_name='레시피 제작자'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='liker',
            field=models.ManyToManyField(related_name='liked_recipe', through='recipes.Like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='sandwich',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingredients.Sandwich', verbose_name='기본 샌드위치'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='sauces',
            field=models.ManyToManyField(to='ingredients.Sauces', verbose_name='소스'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='toasting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingredients.Toasting', verbose_name='토스팅'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='toppings',
            field=models.ManyToManyField(to='ingredients.Toppings', verbose_name='토핑'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='vegetables',
            field=models.ManyToManyField(to='ingredients.Vegetables', verbose_name='야채'),
        ),
        migrations.AddField(
            model_name='like',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='collection',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookmarkcollection.BookmarkCollection'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
