# Generated by Django 2.0.5 on 2018-10-05 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='recipename',
            options={'ordering': ['-pk']},
        ),
    ]
