# Generated by Django 2.0.5 on 2018-07-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandwich',
            name='ordering_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
