# Generated by Django 2.0.5 on 2018-06-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandwich',
            name='image',
            field=models.FilePathField(blank=True, max_length=5000, path='sandwich'),
        ),
    ]
