# Generated by Django 2.0.5 on 2018-06-24 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetables',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bread',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
