# Generated by Django 2.0.5 on 2018-07-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_sandwich_ordering_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandwich',
            name='ordering_num',
            field=models.IntegerField(blank=True),
        ),
    ]
