# Generated by Django 2.0.5 on 2018-06-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20180625_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bread',
            name='image',
            field=models.FilePathField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cheese',
            name='image',
            field=models.FilePathField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sandwich',
            name='image',
            field=models.FilePathField(max_length=255, path='sandwich'),
        ),
        migrations.AlterField(
            model_name='sauces',
            name='image',
            field=models.FilePathField(max_length=255),
        ),
        migrations.AlterField(
            model_name='toppings',
            name='image',
            field=models.FilePathField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vegetables',
            name='image',
            field=models.FilePathField(max_length=255),
        ),
    ]
