# Generated by Django 2.0.5 on 2018-06-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20180618_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='img_profile',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='img_profile_thumbnail',
        ),
        migrations.AddField(
            model_name='sandwich',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
