# Generated by Django 2.0.5 on 2018-06-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20180625_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandwich',
            name='image3x',
            field=models.FilePathField(default='', max_length=255, path='sandwich'),
        ),
    ]
