# Generated by Django 2.1.2 on 2018-10-16 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_bookmark_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='collection',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookmarkcollection.BookmarkCollection'),
        ),
    ]
