# Generated by Django 2.0.5 on 2018-06-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_sandwich_image3x'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandwich',
            name='image3x',
            field=models.FilePathField(max_length=255, path='sandwich'),
        ),
    ]
