# Generated by Django 2.0.5 on 2018-07-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20180720_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetables',
            name='quantity',
            field=models.CharField(choices=[('조금', '조금'), ('보통', '보통'), ('많이', '많이')], default='NO', max_length=2),
        ),
    ]
