# Generated by Django 2.0.5 on 2018-06-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20180625_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='100까지 MainIngredient의 이름을 저장합니다.', max_length=100, unique=True)),
                ('quantity', models.CharField(help_text='100자까지 MainIngredient의 quantity를 저장합니다.', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='sandwich',
            name='main_ingredient',
            field=models.ManyToManyField(blank=True, to='recipes.MainIngredient', verbose_name='구성재료'),
        ),
    ]
