# Generated by Django 2.1.2 on 2018-10-18 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20181017_0520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipename',
            name='user',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipe_name.RecipeName', verbose_name='이름'),
        ),
        migrations.DeleteModel(
            name='RecipeName',
        ),
    ]
