# Generated by Django 2.1.2 on 2018-10-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, unique=True, verbose_name='이름'),
            preserve_default=False,
        ),
    ]
