# Generated by Django 2.0.5 on 2018-07-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20180630_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bread',
            name='name',
            field=models.CharField(help_text='100자까지 Bread 이름을 저장합니다.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='cheese',
            name='name',
            field=models.CharField(help_text='100자까지 Cheese 이름을 저장합니다.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='sauces',
            field=models.ManyToManyField(to='recipes.Sauces', verbose_name='소스'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='toppings',
            field=models.ManyToManyField(to='recipes.Toppings', verbose_name='토핑'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='vegetables',
            field=models.ManyToManyField(to='recipes.Vegetables', verbose_name='야채'),
        ),
    ]
