# Generated by Django 2.0.5 on 2018-07-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20180701_0653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cheese',
            options={'verbose_name_plural': 'cheese'},
        ),
        migrations.AddField(
            model_name='sandwich',
            name='category',
            field=models.ManyToManyField(blank=True, to='recipes.Category', verbose_name='카테고리'),
        ),
    ]
