# Generated by Django 2.0.5 on 2018-05-26 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOAuthID',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='oauthid', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('kakao_id', models.CharField(blank=True, max_length=255)),
                ('facebook_id', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'UserOAuthID',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='img_profile_thumbnail',
            field=models.ImageField(blank=True, upload_to='user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
