# Generated by Django 2.0.5 on 2018-05-26 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180526_0248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useroauthid',
            options={'verbose_name_plural': 'UserOAuthID'},
        ),
    ]
