# Generated by Django 2.1.2 on 2018-11-19 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='vegetables',
            name='quantity',
            field=models.ForeignKey(default='보통', on_delete=django.db.models.deletion.CASCADE, to='ingredients.Quantity'),
        ),
    ]
