# Generated by Django 2.1.2 on 2018-11-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetables',
            name='name',
            field=models.CharField(help_text='100자까지 Vegetable의 이름을 저장합니다.', max_length=100),
        ),
    ]
