# Generated by Django 2.1.2 on 2018-11-19 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_auto_20181119_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetables',
            name='quantity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.Quantity'),
        ),
    ]
