# Generated by Django 2.0.5 on 2018-08-19 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_auto_20180819_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandwich',
            name='calories',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sandwich',
            name='protein',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sandwich',
            name='saturated_fat',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sandwich',
            name='serving_size',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sandwich',
            name='sodium',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sandwich',
            name='sugars',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
