# Generated by Django 2.0.5 on 2018-08-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_auto_20180819_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandwich',
            name='image3x_full',
            field=models.FilePathField(default=1, max_length=255, path='sandwich'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sandwich',
            name='image_full',
            field=models.FilePathField(default=1, max_length=255, path='sandwich'),
            preserve_default=False,
        ),
    ]
