# Generated by Django 2.1.2 on 2018-11-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_auto_20181119_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetables',
            name='quantity',
            field=models.CharField(choices=[('조금', '조금'), ('보통', '보통'), ('많이', '많이')], default='보통', max_length=2),
        ),
    ]
