# Generated by Django 2.1.2 on 2018-11-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_auto_20181119_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetables',
            name='name',
            field=models.CharField(help_text='100자까지 Vegetable의 이름을 저장합니다.', max_length=100),
        ),
    ]
