# Generated by Django 2.0.5 on 2018-09-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_auto_20180819_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='bread',
            name='calories',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cheese',
            name='calories',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
