# Generated by Django 2.1.2 on 2018-10-24 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0007_toppings_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainingredient',
            name='calories',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
