# Generated by Django 2.0.5 on 2018-06-03 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='100자까지의 bread의 이름을 저장합니다.', max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': '선택한 breads',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_profile', models.ImageField(blank=True, upload_to='user')),
                ('img_profile_thumbnail', models.ImageField(blank=True, upload_to='user')),
                ('breads', models.OneToOneField(max_length=3, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Breads', verbose_name='빵')),
                ('product_maker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='레시피 제작자')),
            ],
        ),
        migrations.CreateModel(
            name='Vegetables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='100자까지의 vegetable의 이름을 저장합니다.', max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': '선택한 vegetables',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='vegetables',
            field=models.ManyToManyField(blank=True, to='products.Vegetables', verbose_name='야채'),
        ),
    ]
