# Generated by Django 2.0.5 on 2018-06-06 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='100자까지의 bread의 이름을 저장합니다.', max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': '선택한 bread',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_profile', models.ImageField(blank=True, upload_to='user')),
                ('img_profile_thumbnail', models.ImageField(blank=True, upload_to='user')),
                ('bread', models.OneToOneField(max_length=3, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Bread', verbose_name='빵')),
            ],
        ),
        migrations.CreateModel(
            name='Vegetables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='100자까지의 vegetable의 이름을 저장합니다.', max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': '선택한 vegetables',
            },
        ),
    ]
