# Generated by Django 2.0.5 on 2018-06-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breads', models.CharField(choices=[('WHI', '화이트'), ('HEA', '하티'), ('PAR', '파마산오레가노'), ('WHE', '위트'), ('HON', '허니오트'), ('FLA', '플랫')], max_length=3, verbose_name='빵')),
                ('img_profile', models.ImageField(blank=True, upload_to='user')),
                ('img_profile_thumbnail', models.ImageField(blank=True, upload_to='user')),
            ],
        ),
        migrations.CreateModel(
            name='Vegetables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='100자까지의 vegetable의 이름을 저장합니다.', max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': '선택한 vegetables',
            },
        ),
    ]
