# Generated by Django 2.0.5 on 2018-06-02 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='레시피 제작자'),
        ),
        migrations.AddField(
            model_name='product',
            name='vegetables',
            field=models.ManyToManyField(to='products.Vegetables', verbose_name='야채'),
        ),
    ]
