# Generated by Django 2.0.5 on 2018-06-02 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180602_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_maker',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='레시피 제작자'),
        ),
    ]
