# Generated by Django 2.0.5 on 2018-06-07 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180606_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bread',
            name='name',
            field=models.CharField(help_text='100자까지의 bread의 이름을 저장합니다.', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='bread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Bread', verbose_name='빵'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_maker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='레시피 제작자'),
        ),
    ]
