# Generated by Django 2.0.5 on 2018-06-09 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180607_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='255자까지 product의 이름을 저장합니다.', max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bread',
            name='name',
            field=models.CharField(help_text='100자까지 bread의 이름을 저장합니다.', max_length=100),
        ),
        migrations.AlterField(
            model_name='vegetables',
            name='name',
            field=models.CharField(help_text='100자까지 vegetable의 이름을 저장합니다.', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ProductName', verbose_name='이름'),
        ),
    ]
