# Generated by Django 2.0.5 on 2018-06-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180602_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vegetables',
            field=models.ManyToManyField(blank=True, to='products.Vegetables', verbose_name='야채'),
        ),
    ]
