# Generated by Django 2.0.5 on 2018-06-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20180609_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productname',
            name='name',
            field=models.CharField(help_text='255자까지 product의 이름을 저장합니다.', max_length=255, unique=True),
        ),
    ]
