# Generated by Django 2.0.5 on 2018-06-02 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20180602_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_maker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='레시피 제작자'),
        ),
    ]
