# Generated by Django 2.0.5 on 2018-06-10 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180610_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='100자까지 Product Ingredient의 이름을 저장합니다.', max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='main_ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.MainIngredient', verbose_name='기본 샌드위치'),
        ),
    ]
