# Generated by Django 2.0.5 on 2018-06-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20180610_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
        migrations.AddField(
            model_name='vegetables',
            name='quantity',
            field=models.CharField(choices=[('LE', 'LESS'), ('NO', 'NORMAL'), ('MO', 'MORE')], default='NO', max_length=2),
        ),
    ]
