# Generated by Django 2.0.5 on 2018-07-15 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_date'], 'verbose_name': '공지사항', 'verbose_name_plural': '공지사항 목록'},
        ),
    ]
